### ISSUE TITLE
[Feature] support show structure line

### ISSUE THREAD

**Issue by percy507** [minop1205/react-dnd-treeview#170]
There is an demo from MUI. https://mui.com/x/

<img width="1266" alt="image" src="https://user-images.githubusercontent.com/18365078/203227958-eff8a795-c22c-4e81-bb71-7a086c5568de.png">

**Comment by percy507** [comment]
Referable example: https://iamkate.com/code/tree-views/

**Comment by minop1205** [comment]
@percy507 Thank you for your suggestion.

In react-dnd-treeview, the implementation regarding appearance is left to the user of the library.

The structure line is the part related to appearance, where all kinds of designs exist.

Therefore, I do not include the implementation of the structure line in the library, but would like it to be done by the application that uses the library.

However, since the display of structure lines is a common use case in treeviews, I believe it is necessary to provide sample codes.

In providing samples, I will consider extending the render options, etc., if they cannot be implemented with existing functionality alone.

**Comment by nilesh2b** [comment]
@minop1205 Is it possible to show the tree in horizontal view?

**Comment by abrman** [comment]
> @minop1205 Is it possible to show the tree in horizontal view?

Can you provide an example of what you mean by horizontal view?

**Comment by abrman** [comment]
@percy507 I was interested in something similar as you, so I built this using this react-dnd-treeview component.
Let me know if you're still looking for a MUI similar treeview style.

https://user-images.githubusercontent.com/6663260/212092428-9cb73dcc-0ec7-478b-a72d-13b5a4cdf907.mp4

**Comment by percy507** [comment]
@abrman  Looks great. It will be nice if you can make a PR to add this feature as an example.

**Comment by abrman** [comment]
Right. I'm not sure if I should add it to [stories](https://github.com/minop1205/react-dnd-treeview/tree/next/src/stories) somehow, also think it might be my first PR on a public project ever. lol

Anyways, here's the demo: https://codesandbox.io/s/nifty-farrell-qpq9h3?file=/src/App.tsx

**Comment by percy507** [comment]
> Anyways, here's the demo: https://codesandbox.io/s/nifty-farrell-qpq9h3?file=/src/App.tsx

@minop1205 What do you think about adding this demo to the stories?

**Comment by minop1205** [comment]
@percy507 @abrman Thanks for the great samples!

If you can, please send us a pull request with additional stories and we will review and merge them.

At that time, it would be great if you could add the test as well as the other stories, but if it is difficult, I will add the test on my end.

**Comment by percy507** [comment]
@abrman Be bold and submit your first PR.

**Comment by minop1205** [comment]
@abrman Thank you for your contribution!
Merged: https://github.com/minop1205/react-dnd-treeview/pull/183
Demo: https://minop1205.github.io/react-dnd-treeview/?path=/docs/basic-examples-directory-structure--directory-structure-story
