### ISSUE TITLE
Open method not working

### ISSUE THREAD

**Issue by alialaa** [minop1205/react-dnd-treeview#194]
Using the ref to open a node by its ID doesn't seem to be working. the close method works though. [Here is a demo](https://codesandbox.io/s/competent-saha-j8yhit?file=/src/App.js).

**Comment by minop1205** [comment]
@alialaa Thanks for reporting the bug.

It was caused by the fact that the `open` method was only working on droppable nodes.
It is strange that there is a dependency between `droppable` property and the open/closed state of a node, so I have fixed this issue.

I have just released v3.4.4, so please try the latest version.

```
npm install @minoru/react-dnd-treeview@latest
```
