### ISSUE TITLE
不具合報告：Cannot drag and drop node to root

### ISSUE THREAD

**Issue by chris-oms** [minop1205/react-dnd-treeview#63]
I'd like to be able to take a nested node and drag it to the root (so that it's parent becomes 0). Is this something that can be added?

**Comment by minop1205** [comment]
@chris-oms Yes, it is possible. Please look at the following example.

![example](https://user-images.githubusercontent.com/3772820/132607401-76704bd0-d0dd-4756-bc2c-1f740b0ad4ac.gif)

In this example, I drop a node named `Folder 2-1` into the root.

(in CodeSandbox)
https://codesandbox.io/s/full-features-js-itczn

**NOTE:**
To drop to the root, the route area must have a space. Therefore, you need to set the styles so that the height of the root node is secured.


Do you find the following App.jsx and App.module.css helpful?

App.jsx
https://codesandbox.io/s/full-features-js-itczn?file=/src/App.jsx

App.module.css
https://codesandbox.io/s/full-features-js-itczn?file=/src/App.module.css

**Comment by chris-oms** [comment]
@minop1205 

Thanks for the quick reply, and yes you're completely right! Adding a bit of bottom padding did the trick for me. Thank you.
