### ISSUE TITLE
Feature Request: styling for 1st-level items

### ISSUE THREAD

**Issue by Nerevar123** [minop1205/react-dnd-treeview#81]
# Feature request

Hi @minop1205, is it possible to add the ability to style the top-level list items?

For realisation like this: 

![image](https://user-images.githubusercontent.com/65253367/141271725-e2b3d4a4-f208-4de3-b656-6135ddee2102.png)

**Comment by minop1205** [comment]
@Nerevar123 

Changing the style only for top-level items is possible by using the classes property or the `depth` option of render.

The classes property allows you to define the class name of the root ul, so for example, you can style only the items in the top-level hierarchy with the following selector

```
.rootList > li > div {
  color: #f00;
}
```

Click here for a sample.
https://codesandbox.io/s/full-features-issue81-1-e7ysh

Also, since option is passed to the render callback function, you can use the `depth` parameter in it to know the depth of the node. So it is possible to assign a dedicated className for depth === 0 in a custom node.

Here is a sample
https://codesandbox.io/s/full-features-issue81-2-ibjjp

**Comment by Nerevar123** [comment]
thanks for the detailed answer, did not think about it
